# Generated by Django 2.2.10 on 2020-09-27 10:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='autor',
            field=models.TextField(default='John Doe'),
        ),
        migrations.AddField(
            model_name='article',
            name='createDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.TextField(default='https://drive.google.com/uc?export=view&id=1dQzsqdmBKoLpEzXAHmbJgkrENZmNmHYE'),
        ),
    ]
